---
title: "17q13q: Clonality Analysis (SITKA TREE)"
output:
  html_document:
    toc: true
    toc_float: true
    theme: united
    code_folding: show
---

# **Editing CNV Data for Sitka Binary Matrix**
## *Luminal Epithelial Data*
### LUMI: Library for Generating Data
```{r message=FALSE, warning=FALSE}
#install.packages("tidyverse")
library(tidyverse)
#install.packages("dplyr")
library(dplyr)
# install.packages("readr")
library(readr)
# install.packages("gt")
library(gt)
# install.packages("vroom")
library(vroom)
#install.packages("openxlsx")
library(openxlsx)
#install.packages("ape")
library(ape)
#install.packages("ggtree")
library(ggtree)
#install.packages("ggplot2")
library(ggplot2)
```

### LUMI: Load CNV Data
```{r}
read_cnv_data <- function(filepath) {
#!!!!!!!!!!!!!!!!!!!!!!!!! EDIT RAW FILES !!!!!!!!!!!!!!!!!!!!!!!!!
  #read and process CNV data
  cnv_data <- read.csv(filepath) %>%
    mutate(
      genotype = ifelse(grepl("B1-6548", sample), "B1/B2", sub("-.*", "", sample)), #rename samples
      sample = gsub("-", ".", sample) #rename samples
    ) %>%
    dplyr::select(cell_id, chr, state, A, B, LOH, BAF, sample, genotype, start, end) #filter columns
  
  #read in sample info
  cancer.history <- read.xlsx("~/brca-new/Williams et al./williams-samples.xlsx")
  cancer.history <- cancer.history %>% 
    mutate(patient_id = gsub("-", ".", patient_id)) %>% #rename samples
    dplyr::rename(
                  sample = patient_id,  # correct direction: new = old
                  cancer = current_past_cancer.in.contralateral.breast,
                  tissue = Final.Path.Diagnosis) %>%
    dplyr::select(sample, chemo, cancer, tissue)
  
  #edit sample info
  cancer.history$chemo <- gsub("N/A", "no chemo", cancer.history$chemo) 
  cancer.history$chemo <- gsub("N", "no chemo", cancer.history$chemo) 
  cancer.history$chemo <- gsub("Y", "chemo", cancer.history$chemo) 
  cancer.history$tissue <- gsub("R:", "", cancer.history$tissue) 
  cancer.history$tissue <- gsub("R: ", "", cancer.history$tissue) 
  cancer.history$tissue <- gsub("L: ", "", cancer.history$tissue)
  cancer.history$tissue <- gsub(" UDH", "", cancer.history$tissue)
  cancer.history$tissue <- gsub(" cysts", "", cancer.history$tissue)
  cancer.history$tissue <- gsub(" non-proliferative", "", cancer.history$tissue)
  cancer.history$tissue <- gsub(" ", "", cancer.history$tissue)


  #add sample info to df
  cnv_data <- cnv_data %>%
    left_join(cancer.history, by = "sample")

#!!!!!!!!!!!!!!!!!!!!!!!!! NAME SAMPLE DFS !!!!!!!!!!!!!!!!!!!!!!!!!
  #generate name
  if ("sample" %in% colnames(cnv_data)) {
    sample_name <- unique(cnv_data$sample)[1]
  } else {
    sample_name <- tools::file_path_sans_ext(basename(filepath))
  }

  #assign df and gr to global environment
  assign(paste0(sample_name, "_df"), cnv_data, envir = .GlobalEnv)

  #return sample name
  df = assign(paste0(sample_name, "_df"), cnv_data, envir = .GlobalEnv)
}

#arrange file paths
files <- c(
  "/Users/mahadbihie/brca-new/data_directory/allele_specific_cn/B1HET43-hscn.csv",
  "/Users/mahadbihie/brca-new/data_directory/allele_specific_cn/B1HET49-hscn.csv",
  "/Users/mahadbihie/brca-new/data_directory/allele_specific_cn/B1HET6410-hscn.csv",
  "/Users/mahadbihie/brca-new/data_directory/allele_specific_cn/B1HET6537-hscn.csv",
  "/Users/mahadbihie/brca-new/data_directory/allele_specific_cn/B1HET6548-hscn.csv",
  "/Users/mahadbihie/brca-new/data_directory/allele_specific_cn/B1HET6550-hscn.csv",
  "/Users/mahadbihie/brca-new/data_directory/allele_specific_cn/B2HET16-hscn.csv",
  "/Users/mahadbihie/brca-new/data_directory/allele_specific_cn/B2HET18-hscn.csv",
  "/Users/mahadbihie/brca-new/data_directory/allele_specific_cn/B2HET21-hscn.csv",
  "/Users/mahadbihie/brca-new/data_directory/allele_specific_cn/B2HET23-hscn.csv",
  "/Users/mahadbihie/brca-new/data_directory/allele_specific_cn/B2HET25-hscn.csv",
  "/Users/mahadbihie/brca-new/data_directory/allele_specific_cn/B2HET6532-hscn.csv",
  "/Users/mahadbihie/brca-new/data_directory/allele_specific_cn/WT6-hscn.csv",
  "/Users/mahadbihie/brca-new/data_directory/allele_specific_cn/WT62-hscn.csv",
  "/Users/mahadbihie/brca-new/data_directory/allele_specific_cn/WT6752-hscn.csv"
)

#run pipeline
lapply(files, read_cnv_data)
```

### LUMI: Generate Binary Matrix of Sitka
```{r}
#format luminal CNV data
cnv.lumi <- B2.18_df %>%
  mutate(
    loci = paste(
      chr,
      format(start, scientific = FALSE, trim = TRUE),
      format(end, scientific = FALSE, trim = TRUE),
      sep = "_"
    )
  ) %>%
  group_by(loci, cell_id) %>%
  summarise(state = round(mean(state, na.rm = TRUE)), .groups = "drop") %>%
  pivot_wider(names_from = cell_id, values_from = state) %>%
  column_to_rownames(var="loci")

# Remove any leading/trailing spaces
rownames(cnv.lumi) <- trimws(rownames(cnv.lumi))

# Ensure all values are numeric
cnv.lumi[] <- lapply(cnv.lumi, as.numeric)

#save matrix for Sitka Tree
write.csv(x = cnv.lumi,
          file = "~/sitkatree/example/data/cnv_input.csv",
          quote = FALSE,
          row.names = TRUE)
```

## *TNBC*
### TNBC: Load CNV Data
```{r}
#read in q arm cnv data
load("~/17q13q/data/q_cnv.RData")
```
### TNBC: Generate Binary Matrix of Sitka
```{r}
#format TNBC CNV data
cnv.tnbc <- q_tnbc_cnv %>%
  filter(Sample_Name == "SA501") %>%
  mutate(
    loci = paste(
      chr,
      format(start, scientific = FALSE, trim = TRUE),
      format(end, scientific = FALSE, trim = TRUE),
      sep = "_"
    )
  ) %>%
  group_by(loci, cell_id) %>%
  summarise(state = round(mean(state, na.rm = TRUE)), .groups = "drop") %>%
  pivot_wider(names_from = cell_id, values_from = state) %>%
  column_to_rownames(var="loci")

# Remove any leading/trailing spaces
rownames(cnv.tnbc) <- trimws(rownames(cnv.tnbc))

# Ensure all values are numeric
cnv.tnbc[] <- lapply(cnv.tnbc, as.numeric)

#save matrix for Sitka Tree
write.csv(x = cnv.tnbc,
          file = "~/sitkatree/example/data/cnv_input.csv",
          quote = FALSE,
          row.names = TRUE)
```

# **SITKA Instructions (TERMINAL)**
## *SITKA Code (Terminal)*
```{r}
#Step 0: process CNV data into binary file for SITKA 
Rscript cntob.R -i data/cnv_input.csv -o data/binary.csv

# Step 1: Jitter Correction
~/sitkatree/sitka/build/install/nowellpack/bin/corrupt-straighten \
  --input ~/sitkatree/example/data/binary.csv \
  --neighborhoodSize 2
  
# Step 2: Filter Loci
~/sitkatree/sitka/build/install/nowellpack/bin/corrupt-filter --input results/all/2025-11-06-09-13-35-OxyH6jfm.exec/output.csv --lowerFraction 0.05

#Step 3: Tree Inference
JAVA_TOOL_OPTIONS="--add-opens=java.base/java.util=ALL-UNNAMED" \
~/sitkatree/sitka/build/install/nowellpack/bin/corrupt-infer-with-noisy-params \
    --model.globalParameterization true \
    --model.binaryMatrix ~/sitkatree/example/results/all/2025-11-06-09-14-27-ZV7GFS5m.exec/filtered.csv \
    --model.fprBound 0.1 \
    --model.fnrBound 0.5 \
    --engine PT \
    --engine.initialization FORWARD \
    --engine.nScans 10000 \
    --engine.nPassesPerScan 1 \
    --engine.nChains 10
  
#Step 4a:
~/sitkatree/sitka/build/install/nowellpack/bin/corrupt-average --csvFile results/all/2025-11-06-09-15-04-sIJSXoRI.exec/samples/phylo.csv --logisticTransform false

#Step 4b: move sample files to sample specific folder (use file path above)
cp -r ~/sitkatree/example/results/all/2025-11-06-09-15-04-sIJSXoRI.exec/samples/ ~/17q13q/my-data/b2.18-sitka/
  
#Step 5: 
  ~/sitkatree/sitka/build/install/nowellpack/bin/corrupt-greedy --tipInclusionProbabilities ReadOnlyCLMatrix results/all/2025-11-06-09-17-43-MfDDRX6m.exec/average.csv

#Step 5b: move tree newick to sample specific folder (use new path to newick file)
cp ~/sitkatree/example/results/all/2025-11-06-09-20-45-fRUrKIya.exec/tree.newick ~/17q13q/my-data/b2.18-sitka/
  
cp ~/sitkatree/example/results/all/2025-11-06-09-20-45-fRUrKIya.exec/trees.csv ~/17q13q/my-data/b2.18-sitka/

```


# **Data Visualization**
## *B2.16: APE Visualization*
```{r}
#read the Newick file
tree <- read.tree("~/17q13q/my-data/b2.16-sitka/tree.newick")

# Step 1: Convert deletions to 1, anything else to 0
cnv_filtered <- B2.16_df %>%
  filter(chr %in% c("17","13")) %>%
  mutate(binary = ifelse(state < 2, 1, 0)) %>% 
  dplyr::select(cell_id, chr, binary) %>%
  group_by(cell_id, chr) %>%           # group by cell and chromosome
  summarise(binary = max(binary), .groups = "drop")  # 1 if any deletion, else 0

# Step 2: Pivot to wide format
cnv_wide <- cnv_filtered %>%
  pivot_wider(
    names_from = chr,
    values_from = binary,
    names_prefix = "chr"
  )

#remove cell label on tree
tree$tip.label <- sub("^cell_", "", tree$tip.label)

#make a data frame with tip labels
tip_data <- data.frame(label = tree$tip.label) %>%
  left_join(cnv_wide, by = c("label" = "cell_id"))


#generate tree
tree.17.13 <- ggtree(tree) %<+% tip_data +  # attach metadata
  geom_tiplab(aes(color = case_when(
    chr17 == 1 ~ "17q",
    chr13 == 1 ~ "13q",
    TRUE ~ "none"
  )), size=2) +
  scale_color_manual(   name = "Chromosomal CNV",   values = c("17q" = "red", "13q" = "blue", "none" = "gray70"),   labels = c("17q" = "17q deletion", "13q" = "13q deletion", "none" = "No CNV") ) +
  theme_tree2() +
  ggtitle("B2.16: Phylogenetic Tree with chr17/13 deletions")


#print tree coded with 17q/13q deletions
tree.17.13

#save tree
ggsave(
  filename = "~/17q13q/plots/trees/B2.16-tree.png",  # or "tree_chr17_chr13.png"
  plot = tree.17.13,
  width = 17,      
  height = 17, 
  dpi = 300
)

#generate tree
tree.17.13.circle <- ggtree(tree, layout="circular") %<+% tip_data +  # attach metadata
  geom_tiplab(aes(color = case_when(
    chr17 == 1 ~ "17q",
    chr13 == 1 ~ "13q",
    TRUE ~ "none"
  )), size=2) +
  scale_color_manual(   name = "Chromosomal CNV",   values = c("17q" = "red", "13q" = "blue", "none" = "gray70"),   labels = c("17q" = "17q deletion", "13q" = "13q deletion", "none" = "No CNV") ) +
  theme_tree2() +
  ggtitle("B2.16: Phylogenetic Tree with chr17/13 deletions [Circular]")

#print tree coded with 17q/13q deletions
tree.17.13.circle

#save tree
ggsave(
  filename = "~/17q13q/plots/trees/B2.16-tree-circle.png",
  plot = tree.17.13.circle,
  width = 17,      
  height = 17,     
  dpi = 300
)
```
## *B2.18: APE Visualization*
```{r}
#read the Newick file
tree <- read.tree("~/17q13q/my-data/b2.18-sitka/tree.newick")

# Step 1: Convert deletions to 1, anything else to 0
cnv_filtered <- B2.18_df %>%
  filter(chr %in% c("17","13")) %>%
  mutate(binary = ifelse(state < 2, 1, 0)) %>% 
  dplyr::select(cell_id, chr, binary) %>%
  group_by(cell_id, chr) %>%           # group by cell and chromosome
  summarise(binary = max(binary), .groups = "drop")  # 1 if any deletion, else 0

# Step 2: Pivot to wide format
cnv_wide <- cnv_filtered %>%
  pivot_wider(
    names_from = chr,
    values_from = binary,
    names_prefix = "chr"
  )

#remove cell label on tree
remove cell label on tree tree$tip.label <- sub("^cell_", "", tree$tip.label)

#make a data frame with tip labels
tip_data <- data.frame(label = tree$tip.label) %>%
  left_join(cnv_wide, by = c("label" = "cell_id"))


#generate tree
tree.17.13 <- ggtree(tree) %<+% tip_data +  # attach metadata
  geom_tiplab(aes(color = case_when(
    chr17 == 1 ~ "17q",
    chr13 == 1 ~ "13q",
    TRUE ~ "none"
  )), size=2) +
  scale_color_manual(   name = "Chromosomal CNV",   values = c("17q" = "red", "13q" = "blue", "none" = "gray70"),   labels = c("17q" = "17q deletion", "13q" = "13q deletion", "none" = "No CNV") ) +
  theme_tree2() +
  ggtitle("B2.18: Phylogenetic Tree with chr17/13 deletions")


#print tree coded with 17q/13q deletions
tree.17.13

#save tree
ggsave(
  filename = "~/17q13q/plots/trees/B2.18-tree.png",  # or "tree_chr17_chr13.png"
  plot = tree.17.13,
  width = 17,      
  height = 17, 
  dpi = 300
)

#generate tree
tree.17.13.circle <- ggtree(tree, layout="circular") %<+% tip_data +  # attach metadata
  geom_tiplab(aes(color = case_when(
    chr17 == 1 ~ "17q",
    chr13 == 1 ~ "13q",
    TRUE ~ "none"
  )), size=2) +
  scale_color_manual(   name = "Chromosomal CNV",   values = c("17q" = "red", "13q" = "blue", "none" = "gray70"),   labels = c("17q" = "17q deletion", "13q" = "13q deletion", "none" = "No CNV") ) +
  theme_tree2() +
  ggtitle("B2.18: Phylogenetic Tree with chr17/13 deletions [Circular]")

#print tree coded with 17q/13q deletions
tree.17.13.circle

#save tree
ggsave(
  filename = "~/17q13q/plots/trees/B2.18-tree-circle.png",
  plot = tree.17.13.circle,
  width = 17,      
  height = 17,     
  dpi = 300
)
```
